//! OpenAPI 3.x derived spec for `meka serve`, generated by `utoipa` from the `#[utoipa::path]`
//! annotations on each handler. Served at `GET /v1/openapi.json` and rendered by Swagger UI at
//! `GET /v1/docs`.
//!
//! Keeping the spec inline in the binary (via derive macros rather than a hand-written JSON file)
//! keeps most of it honest: a response type that changes shape changes the schema with it, because
//! the schema is derived from the type.
//!
//! It is not a guarantee, and has drifted. What the macros derive is the *shape*; what a handler
//! actually returns for a given input is prose in the annotation, and prose does not recompile. A
//! status code a handler stopped returning, or started returning, stays as written until someone
//! reads both. Treat an annotation as documentation with a compiler-checked type, not as a proof.

use axum::Router;
use utoipa::{
    Modify, OpenApi,
    openapi::security::{Http, HttpAuthScheme, SecurityScheme},
};
use utoipa_swagger_ui::SwaggerUi;

use crate::server::{handlers, state::ServerState};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "meka HTTP API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Service-to-service API for driving meka agent turns programmatically. \
                       Mirrors the wire format described in the HTTP API docs.",
        license(name = "MIT")
    ),
    paths(
        handlers::sessions::create_session,
        handlers::sessions::fork_session,
        handlers::sessions::list_sessions,
        handlers::sessions::get_session,
        handlers::sessions::patch_session,
        handlers::sessions::delete_session,
        handlers::messages::list_messages,
        handlers::turn::submit_turn,
        handlers::turn::cancel_turn,
        handlers::responses::respond,
        handlers::turn::stream_turn,
        handlers::conversation::compact,
        handlers::conversation::context,
        handlers::conversation::rewind,
        handlers::conversation::export,
        handlers::conversation::import,
        handlers::jobs::list_all,
        handlers::jobs::list_for_session,
        handlers::jobs::create,
        handlers::jobs::cancel,
        handlers::jobs::list_tasks,
        handlers::jobs::cancel_task,
        handlers::stores::get_skill,
        handlers::stores::put_skill,
        handlers::stores::delete_skill,
        handlers::stores::list_memories,
        handlers::stores::get_memory,
        handlers::stores::put_memory,
        handlers::stores::delete_memory,
        handlers::stores::list_tools,
        handlers::stores::instructions,
        handlers::stores::providers,
        handlers::info::info,
        handlers::info::skills,
        handlers::info::mcp,
        handlers::info::mcp_tools,
        handlers::info::mcp_reconnect,
        handlers::discovery::live,
        handlers::discovery::ready,
    ),
    components(schemas(
        crate::server::errors::ProblemDetail,
        crate::server::handlers::sessions::CreateSessionRequest,
        crate::server::handlers::sessions::ForkSessionBody,
        crate::server::handlers::sessions::CapabilitiesBody,
        crate::server::http_frontend::SessionCapabilities,
        crate::server::handlers::sessions::SessionResponse,
        crate::server::handlers::sessions::ListSessionsResponse,
        crate::server::handlers::sessions::PatchSessionRequest,
        crate::server::handlers::turn::TurnRequest,
        crate::server::handlers::turn::ImageInput,
        crate::server::handlers::turn::TurnOptions,
        crate::server::handlers::turn::TurnResponse,
        crate::server::handlers::turn::ToolCallView,
        crate::server::handlers::turn::ToolCallContentView,
        crate::server::handlers::turn::UsageView,
        crate::server::handlers::turn::NoticeView,
        crate::server::handlers::responses::ResponseBody,
        crate::server::handlers::responses::PermissionDecision,
        crate::server::handlers::messages::MessagesResponse,
        crate::server::handlers::messages::MessageView,
        crate::server::handlers::messages::ContentBlockView,
        crate::server::handlers::messages::ToolResultContentView,
        crate::server::handlers::messages::CompactionMarker,
        crate::server::handlers::conversation::CompactRequestBody,
        crate::server::handlers::conversation::CompactResponse,
        crate::server::handlers::conversation::ContextResponse,
        crate::server::handlers::conversation::SessionTotals,
        crate::server::handlers::conversation::RewindRequestBody,
        crate::server::handlers::conversation::RewindResponse,
        crate::server::handlers::conversation::ImportResponse,
        crate::server::handlers::jobs::ScheduledJobView,
        crate::server::handlers::jobs::ScheduledJobsResponse,
        crate::server::handlers::jobs::GateView,
        crate::server::handlers::jobs::CreateJobRequest,
        crate::server::handlers::jobs::CreateGate,
        crate::server::handlers::jobs::BackgroundTaskView,
        crate::server::handlers::jobs::BackgroundTasksResponse,
        crate::server::handlers::stores::SkillDetail,
        crate::server::handlers::stores::WriteSkillRequest,
        crate::server::handlers::stores::MemoryDetail,
        crate::server::handlers::stores::MemoryListResponse,
        crate::server::handlers::stores::SkippedMemoryView,
        crate::server::handlers::stores::WriteMemoryRequest,
        crate::server::handlers::stores::ToolView,
        crate::server::handlers::stores::ToolsResponse,
        crate::server::handlers::stores::InstructionsResponse,
        crate::server::handlers::stores::ProviderView,
        crate::server::handlers::stores::ProvidersResponse,
        crate::server::handlers::info::InfoResponse,
        crate::server::handlers::info::SkillView,
        crate::server::handlers::info::McpServerView,
        crate::server::handlers::info::McpToolView,
        crate::server::handlers::info::McpToolsResponse,
        crate::server::handlers::info::McpReconnectResponse,
        crate::server::handlers::discovery::LiveResponse,
        crate::server::handlers::discovery::ReadyResponse,
    )),
    modifiers(&SecurityAddon),
    tags(
        (name = "sessions", description = "Session CRUD"),
        (name = "turn", description = "Turn lifecycle (submit / re-attach / cancel / mid-turn responses)"),
        (name = "conversation", description = "Compaction, rewind, context occupancy, export / import"),
        (name = "schedule", description = "Scheduled jobs"),
        (name = "tasks", description = "Background tasks"),
        (name = "skills", description = "Skill store CRUD"),
        (name = "memory", description = "Memory store CRUD"),
        (name = "discovery", description = "Server info, tools, instructions, providers, MCP"),
        (name = "health", description = "Liveness / readiness probes"),
    )
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi
            .components
            .get_or_insert_with(utoipa::openapi::Components::default);
        components.add_security_scheme(
            "bearerAuth",
            SecurityScheme::Http(
                Http::builder()
                    .scheme(HttpAuthScheme::Bearer)
                    .description(Some(
                        "Bearer token configured in [[serve.tokens]]. Scopes: sessions:r, \
                         sessions:w, skills:r, skills:w, memory:r, memory:w, schedule:r, \
                         schedule:w, mcp:r, mcp:w.",
                    ))
                    .build(),
            ),
        );
    }
}

/// Wire the OpenAPI JSON endpoint and Swagger UI into the router. Both are public (no bearer
/// auth) so cross-language client tooling can hit them. `SwaggerUi` registers both
/// `/v1/docs/*` and `/v1/openapi.json` itself; no manual route definition is needed.
pub fn router() -> Router<ServerState> {
    Router::new().merge(SwaggerUi::new("/v1/docs").url("/v1/openapi.json", ApiDoc::openapi()))
}
